# GitHub Action para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.
nome : Gerar Cobra

# Controla quando a ação será executada. Esta ação é executada a cada 6 horas.
sobre :
  agendar :
    -cron : " 0 */12 * * * "

# Este comando nos permite executar a ação automaticamente na guia Ações.
  fluxo de trabalho_dispatch :
  empurrar :

# A sequência de execuções neste fluxo de trabalho:
empregos :
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  construir :
    # O tipo de executor em que o trabalho será executado
    executado : ubuntu-mais recente

    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    passos :

    # Verifica o repositório em $GITHUB_WORKSHOP, para que seu trabalho possa acessá-lo
      - usa : ações/checkout@v2

    #Gera a cobra
      - usa : Platane/snk/svg-only@v2
        id : cobra-svg
        com :
          github_user_name : wesley-farias
          # essas próximas 3 linhas geram os arquivos em um branch chamado "output". Isso evita que o ramo principal fique confuso.
          saídas : |
            dist/github-contribution-grid-snake.svg?palette=github-light
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#3c7dd9
            dist/github-contribution-grid-snake-default.svg?color_snake=#3c7dd9&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
     # mostra o status da compilação. Facilita a depuração (se houver algum problema).
      - executar : status do git

      # envia o conteúdo de <build_dir> para um branch
      - nome : envie github-contribution-grid-snake.svg para o branch de saída
        usos : crazy-max/ghaction-github-pages@v2.6.0
        com :
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.ACCESS_TOKEN }}
